### ISSUE TITLE
"errorMessage": "spawn /var/task/node_modules/jpegoptim-bin/vendor/jpegoptim ENOENT",

### ISSUE THREAD

**Issue by rsurenderreddy** [imagemin/imagemin-jpegoptim#15]
Hi i am using imagemin compression on aws lambda, with imagemin-jpegoptim plugin . i am getting below  error.

 "errorMessage": "spawn /var/task/node_modules/jpegoptim-bin/vendor/jpegoptim ENOENT",
    "errorType": "Error",
    "stackTrace": [
        "exports._errnoException (util.js:870:11)",
        "Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)",
        "onErrorNT (internal/child_process.js:344:16)",
        "nextTickCallbackWith2Args (node.js:437:9)",
        "process._tickDomainCallback (node.js:392:17)"

can anyone help on this

**Comment by shinnn** [comment]
`ENOENT` means `jpegoptim` binary was not correctly installed. Reinstall this plugin again.
