### ISSUE TITLE
Spawn - ENOENT error

### ISSUE THREAD

**Issue by alexstoick** [imagemin/imagemin-jpegoptim#9]
I'm currently trying to build one of our packages(https://github.com/Lostmyname/lmn-gulp-tasks/blob/master/tasks/responsive-images.js) on a new machine but I get stuck on this error:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```
I think I have managed to track it down to this line of code: 
https://github.com/imagemin/imagemin-jpegoptim/blob/master/index.js#L11

At this point, the `through` variable is defined, so I'm not sure what could be triggering this.

Any help would be greatly appreciated!

**Comment by kevva** [comment]
It's probably because the binary check failed when you installed this module. What OS are you on?

**Comment by alexstoick** [comment]
Im on OS X 10.10.3 (14D2134)

I reinstalled this after I did a `brew install jpegoptim` which passed, but the library still throws the error.

**Comment by kevva** [comment]
Do you see the binary in your `node_modules/jpegoptim-bin/vendor` folder?

**Comment by alexstoick** [comment]
```./jpegoptim --help
jpegoptim v1.4.1  Copyright (c) Timo Kokkonen, 1996-2014.
Usage: jpegoptim [options] <filenames> 
...
```

**Comment by kevva** [comment]
Hmm, this is weird. Let me check tomorrow on OS X.

**Comment by alexstoick** [comment]
We had a couple of people from the office trying to debug and track this down but with absolutely no success. 

Brand new machine as well, so no previous setup ...

**Comment by kevva** [comment]
Yeah, if the binary works, as it seems, it's probably just some small fix.

**Comment by callumacrae** [comment]
Here is the install error Alex was getting yesterday:

```
npm install jpegoptim-bin
/
> spawn-sync@1.0.11 postinstall /Users/alexstoick/Desktop/lmn-eagle/node_modules/jpegoptim-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync
> node postinstall

|
> jpegoptim-bin@2.0.1 postinstall /Users/alexstoick/Desktop/lmn-eagle/node_modules/jpegoptim-bin
> node lib/install.js

  :warning: The `jpegoptim` binary doesn't seem to work correctly
  :warning: jpegoptim pre-build test failed
  :information_source: compiling from source
  :heavy_multiplication_x: Error: ./configure --prefix="/Users/alexstoick/Desktop/lmn-eagle/node_modules/jpegoptim-bin/vendor" --bindir="/Users/alexstoick/Desktop/lmn-eagle/node_modules/jpegoptim-bin/vendor" && make install && mv /Users/alexstoick/Desktop/lmn-eagle/node_modules/jpegoptim-bin/vendor/bin/jpegoptim /Users/alexstoick/Desktop/lmn-eagle/node_modules/jpegoptim-bin/vendor/jpegoptim
Command failed: 
    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

We had another developer who had the same problem, who reckoned it went away after he left it a few days and tried again—not sure if that's helpful. Could also have been a different issue entirely.

(I work with Alex)

**Comment by evilebottnawi** [comment]
@kevva in debian 7,8 this i have this error too

**Comment by shinnn** [comment]
https://github.com/imagemin/imagemin-jpegoptim/issues/8#issuecomment-141876942
